### ISSUE TITLE
[Bug] 读取启动wda的配置信息时，发现取得变量名不对

### ISSUE THREAD

**Issue by iOrangeTea** [SonicCloudOrg/sonic-gidevice#4]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

main分支latest version

### Deploy platform

MacOS

### Minimal reproduce step

device.go文件，1054-1058行：
if len(xcTestOpt.appOpt) != 0 {
    for k, v := range xcTestOpt.appEnv {
			appOpt[k] = v
		}
	}
这里第1055行，是不是应该为：
for k, v := range xcTestOpt.appOpt {
...

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你可以测试看看，欢迎发起PR修复，一起贡献哦~

**Comment by iOrangeTea** [comment]
已修复
